import { ButtonLink } from '../../../shared/components/Button'
import styles from '../public.module.css'
export function ForCreatorsPage() {
  return <>
    <header><p className="eyebrow">Para creadores</p><h1>Dale a tu idea un lugar para crecer</h1><p className="lead">Prepara una campaña clara: cuenta qué quieres transformar, cómo lo harás y por qué tu comunidad puede confiar en la propuesta.</p><div className={styles.actions}><ButtonLink to="/registro?perfil=creador">Empezar con una cuenta</ButtonLink><ButtonLink variant="secondary" to="/iniciar-sesion">Ya tengo una cuenta</ButtonLink></div></header>
    <section className={styles.section}><h2>Proceso de publicación</h2><div className={styles.grid}>{[
      ['Prepara tu propuesta', 'Define el problema, la solución y los beneficiarios. Organiza la historia, el presupuesto y el impacto esperado de tu campaña.'],
      ['Presenta la información', 'Completa los datos del creador y los respaldos que correspondan. La revisión previa permite comprobar la claridad y consistencia de la propuesta.'],
      ['Comparte y da seguimiento', 'Una vez publicada, comunica la iniciativa y mantén informada a tu comunidad con avances y resultados.']
    ].map(([title, text], i) => <article className={styles.panel} key={title}><span className={styles.number}>{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.section}><h2>¿Qué debes preparar?</h2><div className={styles.twoColumns}><article className={styles.panel}><h3>Sobre tu proyecto</h3><ul className={styles.checklist}><li>Nombre, categoría, ubicación y resumen.</li><li>Historia, problema y solución propuesta.</li><li>Beneficiarios e impacto esperado.</li><li>Plan de trabajo, presupuesto y meta económica.</li><li>Imágenes y una explicación de la modalidad elegida.</li></ul></article><article className={styles.panel}><h3>Sobre el creador</h3><ul className={styles.checklist}><li>Información de la persona u organización responsable.</li><li>Respaldos que correspondan a la propuesta.</li><li>Información coherente para su verificación y revisión.</li><li>Disponibilidad para aclarar observaciones y comunicar avances.</li></ul><p>Los requisitos definitivos y las reglas de aprobación se confirmarán con el equipo responsable. No se realiza verificación real en esta muestra.</p></article></div></section>
    <section className={styles.section}><h2>Tres formas de impulsar una iniciativa</h2><div className={styles.grid}><article className={styles.panel}><h3>Donación</h3><p>Apoyo voluntario a una causa sin una contraprestación material.</p></article><article className={styles.panel}><h3>Recompensa</h3><p>Una campaña que contempla un reconocimiento o beneficio para quienes la apoyan.</p></article><article className={styles.panel}><h3>Preventa</h3><p>Una propuesta productiva que presenta un producto o servicio futuro. Sus condiciones deben explicarse con claridad.</p></article></div></section>
    <section className={styles.hero}><h2>Todo comienza con una propuesta bien contada</h2><p>Crea una cuenta o inicia sesión para conocer el punto de acceso. El editor y el panel privado del creador no forman parte de esta entrega.</p><div className={styles.actions}><ButtonLink to="/registro?perfil=creador">Crear una cuenta</ButtonLink><ButtonLink variant="secondary" to="/iniciar-sesion">Iniciar sesión</ButtonLink></div></section>
  </>
}
